
export const GET_TASKS = 'GET_TASKS';
export const POST_TASK = 'POST_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const PUT_TASK_NAME ='PUT_TASK_NAME';
export const PUT_TASK_STATE ='PUT_TASK_STATE';
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const UPDATE_TASK_NAME_SUCCESS = 'UPDATE_TASK_NAME_SUCCESS';
export const UPDATE_TASK_STATE_SUCCESS = 'UPDATE_TASK_STATE_SUCCESS';
export const GET_TASKS_FAILED = 'GET_TASKS_FAILED';

